/* Copyright (c) SocialLOFT LLC
 * mooSocial - The Web 2.0 Social Network Software
 * @website: http://www.moosocial.com
 * @author: mooSocial
 * @license: https://moosocial.com/license/
 */
var _searchFor = /]:\)|:\(|:D|\(cool\)|:O|;\(|:\(|\(:\||:\||\(kiss\)|:P|;\)|:\$|:\^\)|\|-\)|\(inlove\)|:\)|\(yawn\)|\(puke\)|\(angry\)|\(wasntme\)|\(worry\)|:x|\(devil\)|\(angel\)|\(envy\)|\(meh\)|\(rofl\)|\(happy\)|\(smirk\)|\(beer\)|\(clap\)|\(sun\)|\(flex\)|\(n\)|\(y\)|\(ok\)|\(punch\)|\(\*\)|\(car\)|\(poop\)|\(um\)|\(\^\)|\(d\)|\(f\)|\(mad\)|\(silly\)|\(flu\)|\(ex\)|\(pained\)|\(cup\)|\(m\)|\(candy\)|\(chicken\)|\(cow\)|\(dog\)|\(hih\)|\(e\)|\(bike\)|\(time\)|\(u\)|\(slow\)|\(eat\)|\(corn\)|:evil:|:sad:|:laugh:|:cool:|:surprised:|:crying:|:sweating:|:speechless:|:kiss:|:cheeky:|:wink:|:blushing:|:wondering:|:sleepy:|:inlove:|:smile:|:yawn:|:puke:|:angry:|:wasntme:|:worry:|:love:|:\devil:|:angel:|:envy:|:meh:|:rofl:|:happy:|:smirk:|:beer:|:clap:|:sun:|:flex:|:no:|:yes:|:ok:|:punch:|:star:|:car:|:poop:|:umbrella:|:cake:|:drink:|:football:|:mad:|:silly:|:flu:|:excited:|:pained:|:cup:|:music:|:candy:|:chicken:|:cow:|:dog:|:hih:|:email:|:bike:|:time:|:brokenheart:|:slow:|:eat:|:corn:/gi;
var _map = {
    ']:)': '<span title="evil" id="a48" class="iconos"></span>',
    ':(': '<span title="sad" id="a20" class="iconos"></span>',
    ':D': '<span title="Laugh" id="a1" class="iconos"></span>',
    '(cool)': '<span title="Cool" id="a41" class="iconos"></span>',
    ':O': '<span title="Surprised" id="a50" class="iconos"></span>',
    ';(': '<span title="Crying" id="a24" class="iconos"></span>',
    '(:|': '<span title="Sweating" id="a29" class="iconos"></span>',
    ':|': '<span title="Speechless" id="a52" class="iconos"></span>',
    '(kiss)': '<span title="Kiss" id="a8" class="iconos"></span>',
    ':P': '<span title="Cheeky" id="a39" class="iconos"></span>',
    ';)': '<span title="Wink" id="a6" class="iconos"></span>',
    ':$': '<span title="Blushing" id="a4" class="iconos"></span>',
    ':^)': '<span id="a47" class="iconos"></span>',
    '|-)': '<span title="Sleepy" id="a42" class="iconos"></span>',
    '(inlove)': '<span title="in love" id="a7" class="iconos"></span>',
    ':)': '<span title="smile" id="a3" class="iconos"></span>',
    '(yawn)': '<span title="yawn" id="a43" class="iconos"></span>',
    '(puke)': '<span title="puke" id="a37" class="iconos"></span>',
    '(angry)': '<span title="angry" id="a35" class="iconos"></span>',
    '(wasntme)': '<span title="wasntme" id="a15" class="iconos"></span>',
    '(worry)': '<span title="worry" id="a33" class="iconos"></span>',
    ':x': '<span id="a8" class="iconos"></span>',
    '(devil)': '<span id="a74" class="iconos"></span>',
    '(angel)': '<span title="angel" id="a72" class="iconos"></span>',
    '(envy)': '<span title="envy" id="a19" class="iconos"></span>',
    '(meh)': '<span title="meh" id="a53" class="iconos"></span>',
    '(rofl)': '<span title="rofl" id="a23" class="iconos"></span>',
    '(happy)': '<span id="a18" class="iconos"></span>',
    '(smirk)': '<span id="a57" class="iconos"></span>',
    '(beer)': '<span id="a77" class="iconos"></span>',
    '(clap)': '<span id="a76" class="iconos"></span>',
    '(sun)': '<span id="a2" class="iconos"></span>',
    '(flex)': '<span id="a5" class="iconos"></span>',
    '(n)': '<span id="a9" class="iconos"></span>',
    '(y)': '<span id="a10" class="iconos"></span>',
    '(ok)': '<span id="a11" class="iconos"></span>',
    '(punch)': '<span id="a12" class="iconos"></span>',
    '(*)': '<span id="a13" class="iconos"></span>',
    '(car)': '<span id="a14" class="iconos"></span>',
    '(poop)': '<span title="poop" id="a16" class="iconos"></span>',
    '(um)': '<span title="umbrella" id="a17" class="iconos"></span>',
    '(^)': '<span title="cake" id="a21" class="iconos"></span>',
    '(d)': '<span title="drink" id="a22" class="iconos"></span>',
    '(f)': '<span title="football" id="a25" class="iconos"></span>',
    '(mad)': '<span title="mad" id="a26" class="iconos"></span>',
    '(silly)': '<span title="Silly" id="a27" class="iconos"></span>',
    '(flu)': '<span title="Flu" id="a28" class="iconos"></span>',
    '(ex)': '<span title="Excited" id="a30" class="iconos"></span>',
    '(pained)': '<span title="pained" id="a31" class="iconos"></span>',
    '(cup)': '<span title="cup" id="a32" class="iconos"></span>',
    '(m)': '<span title="music" id="a34" class="iconos"></span>',
    '(candy)': '<span title="candy" id="a36" class="iconos"></span>',
    '(chicken)': '<span title="chicken" id="a38" class="iconos"></span>',
    '(cow)': '<span title="cow" id="a40" class="iconos"></span>',
    '(dog)': '<span title="dog" id="a44" class="iconos"></span>',
    '(hih)': '<span title="hand in hand" id="a45" class="iconos"></span>',
    '(e)': '<span title="Mail" id="a46" class="iconos"></span>',
    '(bike)': '<span title="Bike" id="a49" class="iconos"></span>',
    '(time)': '<span title="Time" id="a50" class="iconos"></span>',
    '(u)': '<span title="Broken heart" id="a51" class="iconos"></span>',
    '(slow)': '<span title="slow" id="a54" class="iconos"></span>',
    '(eat)': '<span title="eat" id="a55" class="iconos"></span>',
    '(corn)': '<span title="corn" id="a56" class="iconos"></span>',
    ':evil:': '<span title="evil" id="a48" class="iconos"></span>',
    ':sad:': '<span title="sad" id="a20" class="iconos"></span>',
    ':laugh:': '<span title="Laugh" id="a1" class="iconos"></span>',
    ':cool:': '<span title="Cool" id="a41" class="iconos"></span>',
    ':surprised:': '<span title="Surprised" id="a50" class="iconos"></span>',
    ':crying:': '<span title="Crying" id="a24" class="iconos"></span>',
    ':sweating:': '<span title="Sweating" id="a29" class="iconos"></span>',
    ':speechless:': '<span title="Speechless" id="a52" class="iconos"></span>',
    ':kiss:': '<span title="Kiss" id="a8" class="iconos"></span>',
    ':cheeky:': '<span title="Cheeky" id="a39" class="iconos"></span>',
    ':wink:': '<span title="Wink" id="a6" class="iconos"></span>',
    ':blushing:': '<span title="Blushing" id="a4" class="iconos"></span>',
    ':wondering:': '<span id="a47" class="iconos"></span>',
    ':sleepy:': '<span title="Sleepy" id="a42" class="iconos"></span>',
    ':inlove:': '<span title="in love" id="a7" class="iconos"></span>',
    ':smile:': '<span title="smile" id="a3" class="iconos"></span>',
    ':yawn:': '<span title="yawn" id="a43" class="iconos"></span>',
    ':puke:': '<span title="puke" id="a37" class="iconos"></span>',
    ':angry:': '<span title="angry" id="a35" class="iconos"></span>',
    ':wasntme:': '<span title="wasntme" id="a15" class="iconos"></span>',
    ':worry:': '<span title="worry" id="a33" class="iconos"></span>',
    ':love:': '<span id="a8" class="iconos"></span>',
    ':devil:': '<span id="a74" class="iconos"></span>',
    ':angel:': '<span title="angel" id="a72" class="iconos"></span>',
    ':envy:': '<span title="envy" id="a19" class="iconos"></span>',
    ':meh:': '<span title="meh" id="a53" class="iconos"></span>',
    ':rofl:': '<span title="rofl" id="a23" class="iconos"></span>',
    ':happy:': '<span id="a18" class="iconos"></span>',
    ':smirk:': '<span id="a57" class="iconos"></span>',
    ':beer:': '<span id="a77" class="iconos"></span>',
    ':clap:': '<span id="a76" class="iconos"></span>',
    ':sun:': '<span id="a2" class="iconos"></span>',
    ':flex:': '<span id="a5" class="iconos"></span>',
    ':no:': '<span id="a9" class="iconos"></span>',
    ':yes:': '<span id="a10" class="iconos"></span>',
    ':ok:': '<span id="a11" class="iconos"></span>',
    ':punch:': '<span id="a12" class="iconos"></span>',
    ':star:': '<span id="a13" class="iconos"></span>',
    ':car:': '<span id="a14" class="iconos"></span>',
    ':poop:': '<span title="poop" id="a16" class="iconos"></span>',
    ':umbrella:': '<span title="umbrella" id="a17" class="iconos"></span>',
    ':cake:': '<span title="cake" id="a21" class="iconos"></span>',
    ':drink:': '<span title="drink" id="a22" class="iconos"></span>',
    ':football:': '<span title="football" id="a25" class="iconos"></span>',
    ':mad:': '<span title="mad" id="a26" class="iconos"></span>',
    ':silly:': '<span title="Silly" id="a27" class="iconos"></span>',
    ':flu:': '<span title="Flu" id="a28" class="iconos"></span>',
    ':excited:': '<span title="Excited" id="a30" class="iconos"></span>',
    ':pained:': '<span title="pained" id="a31" class="iconos"></span>',
    ':cup:': '<span title="cup" id="a32" class="iconos"></span>',
    ':music:': '<span title="music" id="a34" class="iconos"></span>',
    ':candy:': '<span title="candy" id="a36" class="iconos"></span>',
    ':chicken:': '<span title="chicken" id="a38" class="iconos"></span>',
    ':cow:': '<span title="cow" id="a40" class="iconos"></span>',
    ':dog:': '<span title="dog" id="a44" class="iconos"></span>',
    ':hih:': '<span title="hand in hand" id="a45" class="iconos"></span>',
    ':email:': '<span title="Mail" id="a46" class="iconos"></span>',
    ':bike:': '<span title="Bike" id="a49" class="iconos"></span>',
    ':time:': '<span title="Time" id="a50" class="iconos"></span>',
    ':brokenheart:': '<span title="Broken heart" id="a51" class="iconos"></span>',
    ':slow:': '<span title="slow" id="a54" class="iconos"></span>',
    ':eat:': '<span title="eat" id="a55" class="iconos"></span>',
    ':corn:': '<span title="corn" id="a56" class="iconos"></span>'
};
var _mapJson = [
    {"emoji":"]:)","text":"evil","class":"iconos a48"},
    {"emoji":":(","text":"sad","class":"iconos a20"},
    {"emoji":":D","text":"Laugh","class":"iconos a1"},
    {"emoji":"(cool)","text":"Cool","class":"iconos a41"},
    {"emoji":":O","text":"Surprised","class":"iconos a50"},
    {"emoji":";(","text":"Crying","class":"iconos a24"},
    {"emoji":"(:|","text":"Sweating","class":"iconos a29"},
    {"emoji":":|","text":"Speechless","class":"iconos a52"},
    {"emoji":"(kiss)","text":"Kiss","class":"iconos a8"},
    {"emoji":":P","text":"Cheeky","class":"iconos a39"},
    {"emoji":";)","text":"Wink","class":"iconos a6"},
    {"emoji":":$","text":"Blushing","class":"iconos a4"},
    {"emoji":":^)","class":"iconos a47"},
    {"emoji":"|-)","text":"Sleepy","class":"iconos a42"},
    {"emoji":"(inlove)","text":"in love","class":"iconos a7"},
    {"emoji":":)","text":"smile","class":"iconos a3"},
    {"emoji":"(yawn)","text":"yawn","class":"iconos a43"},
    {"emoji":"(puke)","text":"puke","class":"iconos a37"},
    {"emoji":"(angry)","text":"angry","class":"iconos a35"},
    {"emoji":"(wasntme)","text":"wasntme","class":"iconos a15"},
    {"emoji":"(worry)","text":"worry","class":"iconos a33"},
    {"emoji":":x","class":"iconos a8"},
    {"emoji":"(angel)","text":"angel","class":"iconos a72"},
    {"emoji":"(envy)","text":"envy","class":"iconos a19"},
    {"emoji":"(meh)","text":"meh","class":"iconos a53"},
    {"emoji":"(rofl)","text":"rofl","class":"iconos a23"},
    {"emoji":"(happy)","class":"iconos a18"},
    {"emoji":"(smirk)","class":"iconos a57"},
    {"emoji":"(beer)","class":"iconos a77"},
    {"emoji":"(clap)","class":"iconos a76"},
    {"emoji":"(sun)","class":"iconos a2"},
    {"emoji":"(flex)","class":"iconos a5"},
    {"emoji":"(n)","class":"iconos a9"},
    {"emoji":"(y)","class":"iconos a10"},
    {"emoji":"(ok)","class":"iconos a11"},
    {"emoji":"(punch)","class":"iconos a12"},
    {"emoji":"(*)","class":"iconos a13"},
    {"emoji":"(car)","class":"iconos a14"},
    {"emoji":"(poop)","text":"poop","class":"iconos a16"},
    {"emoji":"(um)","text":"umbrella","class":"iconos a17"},
    {"emoji":"(^)","text":"cake","class":"iconos a21"},
    {"emoji":"(d)","text":"drink","class":"iconos a22"},
    {"emoji":"(f)","text":"football","class":"iconos a25"},
    {"emoji":"(mad)","text":"mad","class":"iconos a26"},
    {"emoji":"(silly)","text":"Silly","class":"iconos a27"},
    {"emoji":"(flu)","text":"Flu","class":"iconos a28"},
    {"emoji":"(ex)","text":"Excited","class":"iconos a30"},
    {"emoji":"(pained)","text":"pained","class":"iconos a31"},
    {"emoji":"(cup)","text":"cup","class":"iconos a32"},
    {"emoji":"(m)","text":"music","class":"iconos a34"},
    {"emoji":"(candy)","text":"candy","class":"iconos a36"},
    {"emoji":"(chicken)","text":"chicken","class":"iconos a38"},
    {"emoji":"(cow)","text":"cow","class":"iconos a40"},
    {"emoji":"(dog)","text":"dog","class":"iconos a44"},
    {"emoji":"(hih)","text":"hand in hand","class":"iconos a45"},
    {"emoji":"(e)","text":"Mail","class":"iconos a46"},
    {"emoji":"(bike)","text":"Bike","class":"iconos a49"},
    {"emoji":"(u)","text":"Broken heart","class":"iconos a51"},
    {"emoji":"(slow)","text":"slow","class":"iconos a54"},
    {"emoji":"(eat)","text":"eat","class":"iconos a55"},
    {"emoji":"(corn)","text":"corn","class":"iconos a56"}];
var _mapEmoji = ["]:)",":(",":D","(cool)",":O",";(","(:|",":|","(kiss)",":P",";)",":$",":^)","|-)","(inlove)",":)","(yawn)","(puke)","(angry)","(wasntme)","(worry)",":x","(devil)","(angel)","(envy)","(meh)","(rofl)","(happy)","(smirk)","(beer)","(clap)","(sun)","(flex)","(n)","(y)","(ok)","(punch)","(*)","(car)","(poop)","(um)","(^)","(d)","(f)","(mad)","(silly)","(flu)","(ex)","(pained)","(cup)","(m)","(candy)","(chicken)","(cow)","(dog)","(hih)","(e)","(bike)","(time)","(u)","(slow)","(eat)","(corn)",":evil:",":sad:",":laugh:",":cool:",":surprised:",":crying:",":sweating:",":speechless:",":kiss:",":cheeky:",":wink:",":blushing:",":wondering:",":sleepy:",":inlove:",":smile:",":yawn:",":puke:",":angry:",":wasntme:",":worry:",":love:",":devil:",":angel:",":envy:",":meh:",":rofl:",":happy:",":smirk:",":beer:",":clap:",":sun:",":flex:",":no:",":yes:",":ok:",":punch:",":star:",":car:",":poop:",":umbrella:",":cake:",":drink:",":football:",":mad:",":silly:",":flu:",":excited:",":pained:",":cup:",":music:",":candy:",":chicken:",":cow:",":dog:",":hih:",":email:",":bike:",":time:",":brokenheart:",":slow:",":eat:",":corn:"];
module.exports = {
    replace:function(text){
        text = text.replace(_searchFor, function (match) {

            return (_map.hasOwnProperty(match))?_map[match]:match;
        });
        return text;
    },
    getEmojiHtml:function(){
        return '<span  title="]:)" class="iconos a48"></span><span  title=":(" class="iconos a20"></span><span  title=":D" class="iconos a1"></span><span  title="(cool)" class="iconos a41"></span><span  title=":O" class="iconos a50"></span><span  title=";(" class="iconos a24"></span><span  title="(:|" class="iconos a29"></span><span  title=":|" class="iconos a52"></span><span  title="(kiss)" class="iconos a8"></span><span  title=":P" class="iconos a39"></span><span  title=";)" class="iconos a6"></span><span  title=":$" class="iconos a4"></span><span title=":^)" class="iconos a47"></span><span  title="|-)" class="iconos a42"></span><span  title="(inlove)" class="iconos a7"></span><span  title=":)" class="iconos a3"></span><span  title="(yawn)" class="iconos a43"></span><span  title="(puke)" class="iconos a37"></span><span  title="(angry)" class="iconos a35"></span><span  title="(wasntme)" class="iconos a15"></span><span  title="(worry)" class="iconos a33"></span><span title=":x" class="iconos a8"></span><span title="(devil)" class="iconos a74"></span><span  title="(angel)" class="iconos a72"></span><span  title="(envy)" class="iconos a19"></span><span  title="(meh)" class="iconos a53"></span><span  title="(rofl)" class="iconos a23"></span><span title="(happy)" class="iconos a18"></span><span title="(smirk)" class="iconos a57"></span><span title="(beer)" class="iconos a77"></span><span title="(clap)" class="iconos a76"></span><span title="(sun)" class="iconos a2"></span><span title="(flex)" class="iconos a5"></span><span title="(n)" class="iconos a9"></span><span title="(y)" class="iconos a10"></span><span title="(ok)" class="iconos a11"></span><span title="(punch)" class="iconos a12"></span><span title="(*)" class="iconos a13"></span><span title="(car)" class="iconos a14"></span><span  title="(poop)" class="iconos a16"></span><span  title="(um)" class="iconos a17"></span><span  title="(^)" class="iconos a21"></span><span  title="(d)" class="iconos a22"></span><span  title="(f)" class="iconos a25"></span><span  title="(mad)" class="iconos a26"></span><span  title="(silly)" class="iconos a27"></span><span  title="(flu)" class="iconos a28"></span><span  title="(ex)" class="iconos a30"></span><span  title="(pained)" class="iconos a31"></span><span  title="(cup)" class="iconos a32"></span><span  title="(m)" class="iconos a34"></span><span  title="(candy)" class="iconos a36"></span><span  title="(chicken)" class="iconos a38"></span><span  title="(cow)" class="iconos a40"></span><span  title="(dog)" class="iconos a44"></span><span  title="(hih)" class="iconos a45"></span><span  title="(e)" class="iconos a46"></span><span  title="(bike)" class="iconos a49"></span><span  title="(time)" class="iconos a50"></span><span  title="(u)" class="iconos a51"></span><span  title="(slow)" class="iconos a54"></span><span  title="(eat)" class="iconos a55"></span><span  title="(corn)" class="iconos a56" ></span><span  title=":evil:" class="iconos a48"></span><span  title=":sad:" class="iconos a20"></span><span  title=":laugh:" class="iconos a1"></span><span  title=":cool:" class="iconos a41"></span><span  title=":surprised:" class="iconos a50"></span><span  title=":crying:" class="iconos a24"></span><span  title=":sweating:" class="iconos a29"></span><span  title=":speechless:" class="iconos a52"></span><span  title=":kiss:" class="iconos a8"></span><span  title=":cheeky:" class="iconos a39"></span><span  title=":wink:" class="iconos a6"></span><span  title=":blushing:" class="iconos a4"></span><span title=":wondering:" class="iconos a47"></span><span  title=":sleepy:" class="iconos a42"></span><span  title=":inlove:" class="iconos a7"></span><span  title=":smile:" class="iconos a3"></span><span  title=":yawn:" class="iconos a43"></span><span  title=":puke:" class="iconos a37"></span><span  title=":angry:" class="iconos a35"></span><span  title=":wasntme:" class="iconos a15"></span><span  title=":worry:" class="iconos a33"></span><span title=":love:" class="iconos a8"></span><span title=":devil:" class="iconos a74"></span><span  title=":angel:" class="iconos a72"></span><span  title=":envy:" class="iconos a19"></span><span  title=":meh:" class="iconos a53"></span><span  title=":rofl:" class="iconos a23"></span><span title=":happy:" class="iconos a18"></span><span title=":smirk:" class="iconos a57"></span><span title=":beer:" class="iconos a77"></span><span title=":clap:" class="iconos a76"></span><span title=":sun:" class="iconos a2"></span><span title=":flex:" class="iconos a5"></span><span title=":no:" class="iconos a9"></span><span title=":yes:" class="iconos a10"></span><span title=":ok:" class="iconos a11"></span><span title=":punch:" class="iconos a12"></span><span title=":star:" class="iconos a13"></span><span title=":car:" class="iconos a14"></span><span  title=":poop:" class="iconos a16"></span><span  title=":umbrella:" class="iconos a17"></span><span  title=":cake:" class="iconos a21"></span><span  title=":drink:" class="iconos a22"></span><span  title=":football:" class="iconos a25"></span><span  title=":mad:" class="iconos a26"></span><span  title=":silly:" class="iconos a27"></span><span  title=":flu:" class="iconos a28"></span><span  title=":excited:" class="iconos a30"></span><span title=":pained:" class="iconos a31"></span><span  title=":cup:" class="iconos a32"></span><span  title=":music:" class="iconos a34"></span><span  title=":candy:" class="iconos a36"></span><span  title=":chicken:" class="iconos a38"></span><span  title=":cow:" class="iconos a40"></span><span  title=":dog:" class="iconos a44"></span><span  title=":hih:" class="iconos a45"></span><span  title=":email:" class="iconos a46"></span><span  title=":bike:" class="iconos a49"></span><span  title=":time:" class="iconos a50"></span><span  title=":brokenheart:" class="iconos a51"></span><span  title=":slow:" class="iconos a54"></span><span  title=":eat:" class="iconos a55"></span><span  title=":corn:" class="iconos a56"></span>';
    },
    getEmojiJson:function(){
        return _mapJson;
    },
    isOneEmojiOnly:function(text){
        for (var i=0;i<_mapEmoji.length;i++) {
            if (_mapEmoji[i] == text){
                return true;
            }
        }
        return false;
    }
};
