'use strict';

const ActionTypes = {
    CREATE_INITIATOR_PEER: 'CREATE_INITIATOR_PEER',
    RECEIVE_SIGNAL_FROM_PEER : 'RECEIVE_SIGNAL_FROM_PEER',
    GET_MEDIA_STREAM : 'GET_MEDIA_STREAM',
    SET_MEDIA_STREAM : 'SET_MEDIA_STREAM',
    SET_MEDIA_REMOTE_STREAM : 'SET_MEDIA_REMOTE_STREAM',
    TOOGLE_MY_CAMERA : 'TOOGLE_MY_CAMERA',
    TOOGLE_MY_MIC : 'TOOGLE_MY_MIC',
    SET_MY_CAMERA_ENABLE : 'SET_MY_CAMERA_ENABLE',
    SET_MY_MIC_ENABLE : 'SET_MY_MIC_ENABLE',
    GET_USER_INFO : 'GET_USER_INFO',
    UPDATE_CAMERA_STREAM : 'UPDATE_CAMERA_STREAM',
    CALL_STATUS_RINGING_VIDEO_CALL: 'CALL_STATUS_RINGING_VIDEO_CALL',
    CALL_STATUS_CANCEL_VIDEO_CALL: 'CALL_STATUS_CANCEL_VIDEO_CALL',
    CALL_STATUS_END_VIDEO_CALL: 'CALL_STATUS_END_VIDEO_CALL',
    CALL_STATUS_CANCEL_VIDEO_CALL_RTC: 'CALL_STATUS_CANCEL_VIDEO_CALL_RTC',
    STUN_TURN_SERVER: 'STUN_TURN_SERVER'
};

export default ActionTypes;