DROP TABLE IF EXISTS `{PREFIX}store_attributes`;
DROP TABLE IF EXISTS `{PREFIX}store_order_details`;
DROP TABLE IF EXISTS `{PREFIX}store_orders`;
DROP TABLE IF EXISTS `{PREFIX}store_producers`;
DROP TABLE IF EXISTS `{PREFIX}store_product_attributes`;
DROP TABLE IF EXISTS `{PREFIX}store_product_images`;
DROP TABLE IF EXISTS `{PREFIX}store_product_wishlists`;
DROP TABLE IF EXISTS `{PREFIX}store_products`;
DROP TABLE IF EXISTS `{PREFIX}stores`;
DROP TABLE IF EXISTS `{PREFIX}store_categories`;
DROP TABLE IF EXISTS `{PREFIX}store_product_comments`;
DROP TABLE IF EXISTS `{PREFIX}store_product_reports`;
DROP TABLE IF EXISTS `{PREFIX}store_payments`;
DROP TABLE IF EXISTS `{PREFIX}store_transactions`;
DROP TABLE IF EXISTS `{PREFIX}store_packages`;
DROP TABLE IF EXISTS `{PREFIX}store_shipping_methods`;
DROP TABLE IF EXISTS `{PREFIX}store_shippings`;
DROP TABLE IF EXISTS `{PREFIX}store_shipping_zones`;
DROP TABLE IF EXISTS `{PREFIX}store_shipping_zone_locations`;
DROP TABLE IF EXISTS `{PREFIX}store_shipping_details`;
DROP TABLE IF EXISTS `{PREFIX}store_digital_products`;
DROP TABLE IF EXISTS `{PREFIX}store_reviews`;
DROP TABLE IF EXISTS `{PREFIX}store_review_usefuls`;
DROP TABLE IF EXISTS `{PREFIX}store_product_videos`;
DELETE FROM `{PREFIX}acos` WHERE `group` = 'store';
DELETE FROM `{PREFIX}tasks` WHERE `plugin` = 'Store';
DELETE FROM `{PREFIX}notifications` WHERE `plugin` = 'Store';