/* Copyright (c) SocialLOFT LLC
 * mooSocial - The Web 2.0 Social Network Software
 * @website: http://www.moosocial.com
 * @author: mooSocial
 * @license: https://moosocial.com/license/
 */


module.exports = {
    YES_STRING:"1",
    NO_STRING :"0",
    YES:1,
    NO:0,
    ITEM_HIDE:1,
    ITEM_SHOW:0,
    USER_LOGGED:1,
    USER_LOGOUT:0,
    SOUND_ENABLE:1,
    SOUND_DISABLE:0,
    HIDE_GROUP_ENABLE:1,
    HIDE_GROUP_DISABLE:0,
    APP_IS_USED:1,
    WINDOW_MINIMIZE:1,
    WINDOW_MAXIMIZE:0,
    WINDOW_CHAT_MAXIMIZE_WIDTH:232,
    WINDOW_CHAT_MINIMIZE_WIDTH:163,
    WINDOW_FIRST_CHAT_LEFT_MAGRIN_POSTION:467,
    WINDOW_MINIUM_LEFT_POSTION_ALLOWED_MAXIMIZE:150,
    WINDOW_MESSAGES_IS_LOADED:1,
    WINDOW_MESSAGES_IS_UNLOADED:0,
    USER_ONLINE:'1',
    USER_OFFLINE:'2',
    USER_BUSY:'3',
    USER_INVISIBLE:'4',
    ROOM_IS_UNBLOCKED:0,
    IS_FOCUSED_CHAT_WINDOW:true,
    NOT_FOCUSED_CHAT_WINDOW:false,
    NO_CAMERA_CLOSE_POPUP_TIMEOUT:7000,
    ActionTypes:{
        USER_IS_LOGGED_CALLBACK:'USER_IS_LOGGED_CALLBACK',
        USER_I_CHANGE_ONLINE_STATUS_CALLBACK:'USER_I_CHANGE_ONLINE_STATUS_CALLBACK',
        RECEIVE_RAW_FRIENDS:'RECEIVE_RAW_FRIENDS',
        ADD_RAW_FRIENDS:'ADD_RAW_FRIENDS',
        RECEIVE_RAW_GROUPS:'RECEIVE_RAW_GROUPS',
        SET_ONLINE_FRIENDS:'SET_ONLINE_FRIENDS',
        SET_OFFLINE_FRIENDS:'SET_OFFLINE_FRIENDS',
        SEARCH_FRIEND_CALLBACK:'SEARCH_FRIEND_CALLBACK',
        ADD_RAW_FRIENDS_BY_KEYWORD:'ADD_RAW_FRIENDS_BY_KEYWORD',
        FIND_A_FRIENDS:'FIND_A_FRIENDS',
        CREATE_A_ROOM_FOR_A_USER:'CREATE_A_ROOM_FOR_A_USER',
        CREATE_A_ROOM_FOR_A_USER_BY_USER_CALLBACK:'CREATE_A_ROOM_FOR_A_USER_BY_USER_CALLBACK',
        CREATE_A_ROOM_FOR_A_USER_BY_SYSTEM_CALLBACK:'CREATE_A_ROOM_FOR_A_USER_BY_SYSTEM_CALLBACK',
        CREATE_A_ROOM_BY_ROOM_ID:'CREATE_A_ROOM_BY_ROOM_ID',
        REFESH_A_ROOM_BY_ROOM_ID:'REFESH_A_ROOM_BY_ROOM_ID',
        REFESH_A_ROOM_BY_ROOM_ID_CALLBACK:'REFESH_A_ROOM_BY_ROOM_ID_CALLBACK',
        MARK_MESSAGES_IS_LOADED_FOR_A_ROOM:'MARK_MESSAGES_IS_LOADED_FOR_A_ROOM',
        USER_IS_START_TYPING_IN_A_ROOM:'USER_IS_START_TYPING_IN_A_ROOM',
        USER_IS_STOP_TYPING_IN_A_ROOM:'USER_IS_STOP_TYPING_IN_A_ROOM',
        MARK_MESSAGES_IS_SEEN_IN_ROOMS_CALLBACK:'MARK_MESSAGES_IS_SEEN_IN_ROOMS_CALLBACK',
        ACTIVE_A_ROOM:'ACTIVE_A_ROOM',
        DESTROY_A_ROOM:'DESTROY_A_ROOM',
        DESTROY_ALL_ROOM:'DESTROY_ALL_ROOM',
        MINIMIZE_A_ROOM:'MINIMIZE_A_ROOM',
        CACULATE_NEW_MESSAGES_FOR_ALL_ROOM:'CACULATE_NEW_MESSAGES_FOR_ALL_ROOM',
        RERENDER_ALL_ROOMS:'RERENDER_ALL_ROOMS',
        GET_MESSAGE_FOR_A_ROOM_CALLBACK:'GET_MESSAGE_FOR_A_ROOM_CALLBACK',
        GET_MESSAGE_MORE_FOR_A_ROOM_CALLBACK:'GET_MESSAGE_MORE_FOR_A_ROOM_CALLBACK',
        GET_NEW_MESSAGE_FOR_A_ROOM_CALLBACK:'GET_NEW_MESSAGE_FOR_A_ROOM_CALLBACK',
        DELETE_ALL_MESSAGE_MORE_FOR_A_ROOM:'DELETE_ALL_MESSAGE_MORE_FOR_A_ROOM',
        USER_ADD_CALLBACK:"USER_ADD_CALLBACK",
        STOP_UPDATE_MISSING_USER:"STOP_UPDATE_MISSING_USER",
        POUP_OPEN_REPORT_MODAL:"POUP_OPEN_REPORT_MODAL",
        POUP_OPEN_ALERT_MODAL:"POUP_OPEN_ALERT_MODAL",
        POUP_CLOSE_REPORT_MODAL:"POUP_CLOSE_REPORT_MODAL",
        POUP_CLOSE_ALERT_MODAL:"POUP_CLOSE_ALERT_MODAL",
        POUP_OPEN_ALERT_YES_NO_MODAL:"POUP_OPEN_ALERT_YES_NO_MODAL",
        POUP_CLOSE_ALERT_YES_NO_MODAL:"POUP_CLOSE_ALERT_YES_NO_MODAL",
        POUP_OPEN_RTC_SUPPORTED_ALERT_MODAL:"POUP_OPEN_RTC_SUPPORTED_ALERT_MODAL",
        POUP_CLOSE_RTC_SUPPORTED_ALERT_MODAL:"POUP_CLOSE_RTC_SUPPORTED_ALERT_MODAL",
        POPUP_OPEN_VIDEO_CALL_SETTING_MODAL:"POPUP_OPEN_VIDEO_CALL_SETTING_MODAL",
        POPUP_CLOSE_VIDEO_CALL_SETTING_MODAL:"POPUP_CLOSE_VIDEO_CALL_SETTING_MODAL",
        ADD_USERS_TO_A_ROOM_BY_SYSTEM_CALLBACK:"ADD_USERS_TO_A_ROOM_BY_SYSTEM_CALLBACK",
        COUNTER_UNSEEN_MESSAGES_FROM_RAW_DATA:"COUNTER_UNSEEN_MESSAGES_FROM_RAW_DATA",
        SET_ROOM_MESSAGES_IS_SEEN:"SET_ROOM_MESSAGES_IS_SEEN",
        MARK_READ_ALL_MESSAGES: "MARK_READ_ALL_MESSAGES",
        MOBILE_SHOW_FRIENDS_WINDOW:"MOBILE_SHOW_FRIENDS_WINDOW",
        MOBILE_SHOW_ICON_STATUS:"MOBILE_SHOW_ICON_STATUS",
        MOBILE_SHOW_CHAT_WINDOW:"MOBILE_SHOW_CHAT_WINDOW",
        FRIEND_CHANGE_ONLINE_STATUS_CALLBACK: "FRIEND_CHANGE_ONLINE_STATUS_CALLBACK"
    },
    ModalActions:{
        OPEN_MODAL_REPORT:0,
        CLOSE_MODAL_REPORT:1,
        ON_CLICKED_BUTTON_REPORT_MODAL_REPORT:2
    },
    ERROR:{
        NO_ERROR:0,
        REPORT_ROOM_MESSAGE_SPAM_IS_EXIST:1
    },
    CALL_STATUS:{
        CONTACTING: "contacting",
        RINGING: "ringing",
        NOANSWER: "noanswer",
        RTC_UNSUPPORTED: "rtc_unsupported",
        CALL_ENDED: "call_ended"
    },
    CHAT_MESSAGE_TYPE:{
        TYPE_SYSTEM: "system"
    },
    SYSTEM_MESSAGE_ACTION:{
        MISS_VIDEO_CALL: "miss_video_call"
    },
    ONLINE_STATUS:{
        ACTIVE: "active",
        BUSY: "busy",
        INVISIBLE: "invisible"
    },
};
